name: CI

# Controls when workflow will run
on:
  #Triggers the workflow on push or pull request events
  push:
    branches: [ main ]
    
  #Allows you tu run this workflow manually from Actions tab
  workflow_dispatch:


jobs:
  # This workflow contains a single job called "build"
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup NodeJs
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 16.13.2
          
      - name: Install Mocha for testing
        run: |
          cd src;
          npm install -g mocha;
          npm install
      
  
